# Generated by Django 3.0 on 2022-12-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CookingLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('quote', models.CharField(max_length=1500)),
                ('slug', models.CharField(blank=True, max_length=450, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('steps', models.TextField()),
                ('ingredients', models.TextField()),
                ('preview', models.ImageField(upload_to='preview/')),
                ('views', models.IntegerField(default=0)),
                ('tags', models.CharField(max_length=200)),
                ('author_name', models.CharField(max_length=150)),
                ('author_link', models.CharField(max_length=200)),
                ('CookingTime', models.IntegerField(default=0)),
                ('PortionCounter', models.IntegerField(default=1)),
                ('CaloricContent', models.IntegerField(default=0)),
                ('Squirrels', models.IntegerField(default=0)),
                ('Fats', models.IntegerField(default=0)),
                ('Carbohydrates', models.IntegerField(default=0)),
                ('Water', models.IntegerField(default=0)),
                ('CookingLevel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.CookingLevel')),
                ('KitchenType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.KitchenType')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.Category')),
            ],
        ),
    ]
