# Generated by Django 3.0 on 2022-12-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='CaloricContent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Carbohydrates',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Fats',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Squirrels',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Water',
            field=models.FloatField(default=0),
        ),
    ]
