# Generated by Django 3.0 on 2022-12-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221217_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookinglevel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kitchentype',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
