# Generated by Django 3.0 on 2022-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20221217_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='CaloricContent',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Carbohydrates',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Fats',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Squirrels',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Water',
            field=models.CharField(max_length=400),
        ),
    ]
